/**
 * Augment Express Request with a `correlationId` field for request tracing.
 * The correlation ID is generated by middleware in index.ts and included in
 * all structured log entries for the request (Guidelines §9).
 */
declare namespace Express {
  interface Request {
    correlationId?: string;
  }
}
