/**
 * Augment Express Request with a `correlationId` field for request tracing.
 * The correlation ID is generated by middleware in index.ts and included in
 * all structured log entries for the request (Guidelines §9).
 *
 * This file must stay free of top-level `import`/`export` statements. It is an
 * ambient script, and the moment it gains one it becomes a module — at which
 * point these declarations stop applying globally and every `req.correlationId`
 * in the codebase fails to compile. The inline `import(...)` type below is a
 * type-level expression, not an import statement, so it is safe here; anything
 * needing a real import belongs in its own `.d.ts` (see express-session.d.ts).
 */
declare namespace Express {
  interface Request {
    correlationId?: string;
    /**
     * Authorization resolved for this request by `middleware/authorize.ts`.
     * Never read from the session — see auth/authorization.ts.
     */
    authz?: import('../auth/authorization.js').AuthProfile;
  }
}
